# Generated by Django 3.1.7 on 2021-03-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Alumnos', models.IntegerField()),
                ('temp', models.IntegerField()),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
